trigger:
- master
- feature/*
#put your variabe names 
variables:
 technology: 'springboot'

resources:
  repositories:
  - repository: applicationtemplates
    type: git
    name: applicationtemplates

stages:
- stage: javabuild
  displayName: javabuild
  jobs:
  - template: javabuild.yaml@applicationtemplates
  condition: eq('${{ variables.technology }}', 'java')
- stage: dotnetbuild
  displayName: dotnetbuild
  jobs:
  - template: dotnetbuild.yaml@applicationtemplates
  condition: eq('${{ variables.technology }}', 'dotnet')
- stage: springbootbuild
  displayName: springbootbuild
  jobs:
  - template: springbootbuild.yaml@applicationtemplates
  condition: eq('${{ variables.technology }}', 'springboot')
